### ISSUE TITLE
font and locale

### ISSUE THREAD

**Issue by EKE00372** [CucFlavius/scenemachine#2]
Addon use a font without CJK, will have display issue once get translate.

Suggest add a check for client locale, when it's koKR/zhTW/zhCN then use blizzard defualt font setting, such like `STANDARD_TEXT_FONT`

**Comment by CucFlavius** [comment]
Will do, thanks!

**Comment by EKE00372** [comment]
Nope, ARHei.ttf only use in zhCN, zhTW should use blei00d.TTF

**Comment by CucFlavius** [comment]
Fixed, is this ok? 
![image](https://github.com/CucFlavius/scenemachine/assets/15955757/03061baf-cc74-4b7d-b7f2-88e3d93a2286)

**Comment by EKE00372** [comment]
sure!

thanks, I'll pr translate fix when have time
